ローカライズに対応
tricore-as07/KenKenPa pull request #18
Opened 2020-08-19 09:26 UTC by tricore-as07

英語のローカライズに対応しました。
タイトルに設定ボタンを追加するのと共にアイコンにできるものは
アイコンにまとめました。（設定以外未実装です）
その他、実装確認時に出たバグを修正しました。

2020-08-19 09:37 UTC, tricore-as05 commented
[Q]
i2localizeは使わないのですか？

2020-08-19 09:39 UTC, tricore-as05 requested changes
[MUST]
「言語」の文字がローカライズされていない

2020-08-19 09:48 UTC, tricore-as07 commented
> [MUST]
> 設定画面の「言語」の文字がローカライズされていない

修正しました

2020-08-20 01:47 UTC, tricore-as07 commented
> [Q]
> i2localizeは使わないのですか？

ゲームの使用上タイトルでしか言語変更が出来ないので、
ゲーム開始時にI2でローカライズした文字列を取得して動的に変化する文字列と合わせて表示することで修正しました。

2020-08-20 01:50 UTC, tricore-as05 approved these changes
LGTM

2020-08-20 03:28 UTC, tricore-as03 approved these changes
確認しました。
問題なかったです。

2020-08-20 03:28 UTC, merged