Change game system
tricore-as07/KenKenPa pull request #22
Opened 2020-09-07 09:28 UTC by tricore-as07

審査に提出するための修正、調整、新規実装を行いました。

新規実装内容
・ゲーム開始前、ゲームの制限時間が少なくなった時のカウントダウンアニメーション作成
・一定コンボ数でのボーナスタイム、残り時間が規定値に達した時に最大コンボに応じてボーナスタイムが追加されるシステム
・音量調整のUIとシステムの作成
・ゲーム中にアプリケーションを中断して開いた時にポーズしてタップしたらゲームを再開するように

修正、調整内容
・入力にInputTouchesを使用しないように変更
・バナー広告をNendのみに
・プレイヤーの移動にLerpを使用
・リトライした後だとカウントダウン中に入力ができる不具合の修正

2020-09-08 01:51 UTC, tricore-t-yui requested changes

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/GamePlayManager.cs
> +        player.GetComponent<PlayerInput>().enabled = true;
[IMO]
直でGetComponentしたらnull時にエラーが出た時分からない
あとGetComponent重いので何度も呼ばれないように注意。基本的にはSerializeFieldで

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/InputtableIsByObjectLookChange.cs
> +        transform.GetChild(HitObject).gameObject.SetActive(true);
[IMO]
GetChildもchild以下全コンポーネント検索するので基本的には非推奨
毎度するのではなくキャッシュする

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +        sideInputDistSetting = Screen.width / 5;
[MUST]
調整する項目だと思うので直値ではなく調整可能な変数として準備するべき

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +            bool isTapCenter = Screen.width / 3 < touch.position.x && touch.position.x < Screen.width / 3 * 2;
[MUST]
これも値直打ちでよくない

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +        Invoke("ShowStop", showTime);
[MUST]
文字列Invokeはバグの元
語タイプや関数名変更で即座に動かなくなる
どうしてもやりたい場合はconstで定義

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Sound/SEVolumeSetter.cs
> +    [SerializeField] AudioSource SEaudioSource;
[MUST]
命名規則が守られていない
キャメルケースではaudioSourceSeでは

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/PauseManager.cs
> +                player.GetComponent<PlayerInput>().enabled = false;
[IMO]
ここも直GetComponent

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/PauseManager.cs
> +                player.GetComponent<PlayerInput>().enabled = true;
[MUST]
ここはUpdateなのでGetComponentキャッシュ必須
連打するだけ重くなる

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if (limitTime <= 10.5 && !EndCountDownObject.activeSelf)
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime <= 11.0 && !isAddTimeBonus)
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime > 10.5)
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            nowTime -= (float)(1.0 / 11.0);
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == "Japanese")
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        else if(LocalizationManager.CurrentLanguage == "English")
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
[MUST]
定数

2020-09-08 01:51 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
[MUST]
定数

2020-09-08 01:52 UTC, tricore-as05 requested changes
直さなくてもいいのですが、
Volume、VolumeSetter系は、useKeyをenumに直して[SerializeField]で指定してあげれば共通のスクリプトでできそうな気がします。
あと全体的に変数コメント忘れが多いので気を付けてください。

2020-09-08 01:52 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/FadeOutCanvas.cs
> +    [SerializeField] GameObject CountDown;
[nits]
変数コメント抜け

2020-09-08 01:52 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    [SerializeField] TextMeshProUGUI meshPro;
[nits]
変数コメント忘れ
した二つも

2020-09-08 01:52 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    void ShowStop()
[nits]
関数コメント忘れ

2020-09-08 01:52 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime <= 11.0 && !isAddTimeBonus)
[MUST]
11.0などは直打ちではなくできるだけ変数に

2020-09-08 02:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/InputtableIsByObjectLookChange.cs
> +        transform.GetChild(HitObject).gameObject.SetActive(true);
修正しました。

2020-09-08 03:01 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/GamePlayManager.cs
> +        player.GetComponent<PlayerInput>().enabled = true;
修正しました。

2020-09-08 09:30 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +            bool isTapCenter = Screen.width / 3 < touch.position.x && touch.position.x < Screen.width / 3 * 2;
修正しました。

2020-09-08 09:33 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +        Invoke("ShowStop", showTime);
コルーチンで遅延処理を実装することで修正しました。

2020-09-08 09:40 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Sound/SEVolumeSetter.cs
> +    [SerializeField] AudioSource SEaudioSource;
大石さんの指摘でVolume系を共通のスクリプトにして修正しました。

2020-09-08 09:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/PauseManager.cs
> +                player.GetComponent<PlayerInput>().enabled = false;
修正しました。

2020-09-08 09:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/PauseManager.cs
> +                player.GetComponent<PlayerInput>().enabled = true;
修正しました。

2020-09-08 09:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if (limitTime <= 10.5 && !EndCountDownObject.activeSelf)
修正しました。

2020-09-08 09:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime <= 11.0 && !isAddTimeBonus)
修正しました。

2020-09-08 09:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime > 10.5)
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            nowTime -= (float)(1.0 / 11.0);
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == "Japanese")
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        else if(LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
修正しました。

2020-09-08 09:42 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-08 09:43 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/FadeOutCanvas.cs
> +    [SerializeField] GameObject CountDown;
修正しました。

2020-09-08 09:43 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    [SerializeField] TextMeshProUGUI meshPro;
修正しました。

2020-09-08 09:43 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +            if(limitTime <= 11.0 && !isAddTimeBonus)
修正しました。

2020-09-08 09:44 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    void ShowStop()
処理が一つだけだったので遅延処理用のコルーチンを作って修正しました。

2020-09-09 01:13 UTC, tricore-t-yui requested changes

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/CreateStageSystem/StageCreater.cs
> +                    var rotNum = 12;
[MUST]
クラス頭にconstで準備する
このままだと定数ではなく変数

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int leftWidth = Screen.width / 3;              //画面の左側と中央を区別するライン
[MUST]
readonlyではなくconstにできるものはconstにする
コンパイル結果でのメモリ配置が違う

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +        sideInputDistSetting = Screen.width / sideInputDistOfScreenSplitNum;
[Q]
これも定数にできそうでは？

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    /// <returns></returns>
[MUST]
空Return説明はだめ
Enumrator等返す値が明らかな場合はコメント自体消してもいいかも

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Sound/VolumeSetter.cs
> +
[nits]
不要な空白

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == LanguageType.Japanese.ToString())
[MUST]
ToStringは重い
enum使いたいなら、enumの代入値をstringにできたような

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
[MUST]
文字直接いれてるので定数化されていません
どこかのクラスにpublic定数として準備して使いまわすべきかと

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
[MUST]
文字直接いれてるので定数化されていません
どこかのクラスにpublic定数として準備して使いまわすべきかと

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
同上

2020-09-09 01:13 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
同上

2020-09-09 01:15 UTC, tricore-t-yui requested changes

2020-09-09 01:15 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/GamePlayManager.cs
> +            return;
[IMO]
コード途中でreturnする場合はコメントを記入する
またはなるべく早期return以外でreturn使わない

2020-09-09 01:16 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        else if(LocalizationManager.CurrentLanguage == "English")
MUST]
文字直接いれてるので定数化されていません
どこかのクラスにpublic定数として準備して使いまわすべきかと

2020-09-09 01:21 UTC, tricore-as03 requested changes
全体的にコメントが少ないです。
関数内でひとつの処理を行っている場合は関数コメントに説明を、複数の処理を行っている場合はその処理の頭に説明を追加するとよいです。

2020-09-09 01:21 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/FadeOutCanvas.cs
> +    [SerializeField] GameObject CountDown;                  //カウントダウンのオブジェクト
[IMO]
先頭が大文字になっている。

2020-09-09 01:21 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int rightWidth = Screen.width / 3 * 2;         //画面の右側と中央を区別するライン
[IMO]
値を定数化すると分かりやすい

2020-09-09 01:24 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int leftWidth = Screen.width / 3;              //画面の左側と中央を区別するライン
Screen.widthが実行環境によって値が変わる値のためreadonlyにしていました。

2020-09-09 01:59 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == LanguageType.Japanese.ToString())
enumの代入値を直接stringにするものは見つからず、カスタム属性として文字列を設定するものは見つかったのですが、
文字列を取得する中で結局ToStringを使っているものでした。
このような場合は連想配列的なものを使うべきなのでしょうか？

2020-09-09 02:11 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == LanguageType.Japanese.ToString())
基本的にはDictionaryを使いますね

2020-09-09 03:20 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int rightWidth = Screen.width / 3 * 2;         //画面の右側と中央を区別するライン
申し訳ありません、Screen.widthがスマホの端末によって変わるため
constにできなくてreadonlyで定数化していたつもりだったのですが修正したほうがよろしいでしょうか？

2020-09-09 03:27 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int rightWidth = Screen.width / 3 * 2;         //画面の右側と中央を区別するライン
説明不足で申し訳ありません。
その定数内の３や２を定数化すると分かりやすい、ということです。
今の状態だとなぜwidthを３で割っているのかが分かりにくいので。
名前を付けづらいのであれば、コメントで捕捉すると良いです。

2020-09-09 03:57 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int rightWidth = Screen.width / 3 * 2;         //画面の右側と中央を区別するライン
申し訳ありません、コメントで補足する形で修正しました。
分かりやすくなっているか確認をお願いします。

2020-09-09 03:57 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        else if(LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-09 03:57 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        if (LocalizationManager.CurrentLanguage == "Japanese")
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/TitleImage.cs
> +        else if (LocalizationManager.CurrentLanguage == "English")
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/CreateStageSystem/StageCreater.cs
> +                    var rotNum = 12;
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +        sideInputDistSetting = Screen.width / sideInputDistOfScreenSplitNum;
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    /// <returns></returns>
修正しました。

2020-09-09 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Sound/VolumeSetter.cs
> +
修正しました。

2020-09-09 03:59 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Title/LanguageSetting.cs
> +        if(LocalizationManager.CurrentLanguage == LanguageType.Japanese.ToString())
修正しました。

2020-09-09 04:00 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/GamePlayManager.cs
> +            return;
フェイクロードの処理を別関数に移すことで早期リターン目的だとわかりやすくする形で修正しました。

2020-09-09 04:00 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/FadeOutCanvas.cs
> +    [SerializeField] GameObject CountDown;                  //カウントダウンのオブジェクト
修正しました。

2020-09-09 04:01 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Player/PlayerInput.cs
> +    readonly int rightWidth = Screen.width / 3 * 2;         //画面の右側と中央を区別するライン
確認しました。
問題ないと思います。

2020-09-09 06:10 UTC, tricore-as07 commented
> 全体的にコメントが少ないです。
> 関数内でひとつの処理を行っている場合は関数コメントに説明を、複数の処理を行っている場合はその処理の頭に説明を追加するとよいです。

関数内でコメントが無いと分かりにくそうなところはコメントを追加しました。

2020-09-09 07:17 UTC, tricore-as03 approved these changes
確認しました。

2020-09-10 03:14 UTC, tricore-as05 approved these changes
LGTM

2020-09-10 03:27 UTC, tricore-t-yui requested changes
must一件
念のため指摘
レビュー中はレビュー修正と関係ないコミットをいれないように
全部レビューやり直しになるので

2020-09-10 03:27 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/InputtableIsByObjectLookChange.cs
> +        if (transform.childCount < hitObjectNum)
[MUST]
早期returnじゃないならコメントを

2020-09-10 03:47 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/InputtableIsByObjectLookChange.cs
> +        if (transform.childCount < hitObjectNum)
修正しました。

2020-09-10 03:48 UTC, tricore-as07 commented
> must一件
> 念のため指摘
> レビュー中はレビュー修正と関係ないコミットをいれないように
> 全部レビューやり直しになるので

申し訳ありません、以後気をつけます。

2020-09-10 03:53 UTC, tricore-t-yui approved these changes
LGTM
まだまだ確認箇所が多い…できればもう少し小分けにPRを

2020-09-10 03:53 UTC, merged