コンボが増えた時の見た目を派手に
tricore-as07/KenKenPa pull request #23
Opened 2020-09-11 07:59 UTC by tricore-as07

・コンボ関連を表示する場所を中央に変更しました。
・コンボ数に応じてマテリアルを変更し、見た目が派手になるようにしました。
・コンボ増加時にUIをアニメーションさせるようにしました。
・ミスした時のUIをアニメーションさせるようにしました。

2020-09-11 08:24 UTC, tricore-as05 approved these changes
LGTM

2020-09-11 08:36 UTC, tricore-t-yui requested changes

2020-09-11 08:36 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    [SerializeField] List<ComboBonusUiSetting> comboBonusSettings   //コンボボーナスのオブジェクトを設定するリスト
[nits]
SerializeFieldならdefaultで勝手にリスト入るよ

2020-09-11 08:36 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +        StartCoroutine(DelayMethod(showTime, () =>
[IMO]
いちいちDelayMethod作らなくても
(IEnumrator) => { yieldReturn new WaitForSeconds(showTime); gameObject.SetActive(false); }
でよさそう

ちなみに、オブジェクトのキャプチャが起こるのであんまりラムダ式内でメンバ変数使うのはよくない
メモリのアロケーションが発生します

2020-09-11 08:36 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +        StartCoroutine(DelayMethod(showTime, () =>
DelayMethodみたいな大きな名前なら汎用機能としてどっかに入れるべきとも思う

2020-09-11 08:36 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/ComboCounter.cs
> +        //よくアクセスするコンポーネントをキャッシュしておく
[MUST]
この設計は非常によくない
だれでもコンポーネントにアクセスできることになるので、スパゲティ化待ったなし
責任者を立てるか、コンボカウンター事態ゲーム内で一人しか存在してほしくないなら、SingletonなMonobeviourの実装をする必要がある

2020-09-11 08:58 UTC, tricore-as03 approved these changes
確認しました。

2020-09-11 09:45 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/ComboCounter.cs
> +        //よくアクセスするコンポーネントをキャッシュしておく
コンボに変更があった時の処理だけなので、InputTochesを参考にイベント駆動の処理に変えてみました。
確認をおねがいします。

2020-09-14 07:22 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +    [SerializeField] List<ComboBonusUiSetting> comboBonusSettings   //コンボボーナスのオブジェクトを設定するリスト
修正しました、後ほど別ブランチにて他スクリプトも修正しておきます。

2020-09-14 07:25 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/ShowComboBonusUI.cs
> +        StartCoroutine(DelayMethod(showTime, () =>
別のコルーチンに合わせる形でこの関数を使わないようにして修正しました。
（上記のラムダ式の形で実装しようとしましたが、関数の返り値変更しないといけないというエラーの解決方法が
わからず、断念しました。）

2020-09-14 07:39 UTC, tricore-t-yui approved these changes
何点かコメントあるも基本的にはApprove

2020-09-14 07:39 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/ComboMaterialDecider.cs
> +        = new List<ComboMaterialUiSetting>();
[nits]
これもdefaultでインスタンス入る

2020-09-14 07:39 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/ComboUI.cs
> +        addAnimator = sccessObj.GetComponent<Animator>();
[IMO]
この辺Getせずに直接SerializeFieldにしてもいい気はする
設定外れるリスクとめんどくささと最初にGetComponentする負荷を天秤にかけると、今の実装がいいとは思う

2020-09-14 07:39 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/UI/ShowComboBonusUI.cs
> +    [SerializeField] List<ComboBonusUiSetting> comboBonusSettings;  //コンボボーナスのオブジェクトを設定するリスト
[Q]
default入れ忘れで警告でているのでは

2020-09-14 07:39 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/ComboCounter.cs
> +    public static event OnSuccessComboEvent onSuccessComboEvent;    //コンボを成功させた時に呼ぶイベント
[nits]
public解放してるからいつでもだれでもイベント全削除とかできちゃうのが若干気になるけど、そこまでみんながいじるところでもないしInput.Touchとかもやっちゃってるし指摘だけしておきます
修正不要
前より全然いい設計です

2020-09-14 09:42 UTC, tricore-as05 approved these changes
LGTM

2020-09-14 10:26 UTC, merged