最大コンボボーナスの表示を豪華に
tricore-as07/KenKenPa pull request #26
Opened 2020-09-18 09:14 UTC by tricore-as07

・最大コンボボーナスを表示するオブジェクトを別に作成しました。
・最大コンボボーナス用のアニメーションを作成しました。
・以前いれようとしていたコンボ数に応じて表示するUIとシステムが残っていたので削除しました。

2020-09-18 10:59 UTC, tricore-as03 approved these changes
IMOあるけどApprove

2020-09-18 10:59 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/UI/MaximumComboBonus.cs
> +        }
[IMO]
なんの処理をしているのかコメントが欲しいです。
breakしている理由もお願いします。

2020-09-18 11:06 UTC, tricore-as05 requested changes

2020-09-18 11:06 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +                specialComboBonus.GetComponent<ShowComboBonusUI>().SetBonusTime((int)bonusTime);
[MUST]
specialComboBonusをShowComboBonusUI型にしてしまえばGetComponentする必要ないと思います

2020-09-23 01:20 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/MaximumComboBonus.cs
> +        }
修正しました

2020-09-23 01:20 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/Timer.cs
> +                specialComboBonus.GetComponent<ShowComboBonusUI>().SetBonusTime((int)bonusTime);
修正しました

2020-09-23 05:21 UTC, tricore-as05 approved these changes
LGTM

2020-09-23 07:55 UTC, merged