動画広告の実装
tricore-as07/KenKenPa pull request #29
Opened 2020-09-28 03:24 UTC by tricore-as07

・UnityAdsを使用してのテスト動画広告を表示出来るようにしました。
・ゲームプレイ開始時、5回に1回動画広告を表示してそれ以外はネイティブ広告を表示するようにしました。

2020-09-28 05:15 UTC, tricore-t-yui requested changes

2020-09-28 05:15 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/System/FakeLoadManager.cs
> +    [SerializeField] int movieAdPlayNum;                                //動画広告を表示するプレイ回数
[MUST]
defalut警告出る

2020-09-28 06:51 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/System/FakeLoadManager.cs
> +    [SerializeField] int movieAdPlayNum;                                //動画広告を表示するプレイ回数
その他のスクリプトのdefault警告も含めて修正しました。

2020-09-28 07:40 UTC, tricore-t-yui approved these changes
LGTM

2020-09-28 08:11 UTC, tricore-as03 approved these changes
LGTM

2020-09-28 09:11 UTC, tricore-as05 approved these changes
LGTM

2020-09-29 03:49 UTC, tricore-as07 commented
動画広告を表示した後にゲームが始まらないバグを修正しました。

2020-09-29 05:51 UTC, tricore-as05 approved these changes
LGTM

2020-09-30 00:36 UTC, tricore-as03 approved these changes
LGTM

2020-09-30 00:37 UTC, merged